import { Poppins } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/header';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { Toaster } from 'sonner';

// Load Poppins font
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] });

export const metadata = {
  title: 'Uproute',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      {/* ← force the `dark` class on the root <html> */}
      <html lang="en" className="dark" suppressHydrationWarning>
        <head>
          {/* optional: tell form controls & scrollbars to stay dark */}
          <meta name="color-scheme" content="dark" />
        </head>
        {/* no need to let ThemeProvider switch you back to light */}
        <body className={`${poppins.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"         // ← always start in dark
            enableSystem={false}        // ← ignore system setting
            disableTransitionOnChange
          >
            <Header />
            <main className="min-h-screen">{children}</main>
            <Toaster richColors />
            <footer className="bg-muted/50 py-4">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made with Love by Aniket</p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
